-d C:\Users\Otkuda\Documents\Polytech\dsp_gowin\dsp_test\impl\gwsynthesis\dsp_test.vg
-p GW1N-9C-LQFP144-6
-pn GW1N-LV9LQ144C6/I5
-cfg C:\Users\Otkuda\Documents\Polytech\dsp_gowin\dsp_test\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
